### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by sachin-suresh-rapyuta** [arkadianriver/sphinx-translate-test#2]
On running the run.sh script, I get the below error trace:

```
...
...
Translated 55% of the lines.
Translated 56% of the lines.
Translated 57% of the lines.
Translated 58% of the lines.
Traceback (most recent call last):
  File "/home/sachin/Workspace/Sootballs/Translation_script/translate-po-recursive-src-dest/translate_script.py", line 7, in <module>
    run(
  File "/home/sachin/Workspace/Sootballs/Translation_script/translate-po-recursive-src-dest/translate_po/main.py", line 61, in run
    solve(os.path.join(arguments.dest, relative_path, file), os.path.join(root, file), arguments)
  File "/home/sachin/Workspace/Sootballs/Translation_script/translate-po-recursive-src-dest/translate_po/main.py", line 27, in solve
    line.msgstr = polib.unescape(translate(polib.escape(line.msgid), arguments))
  File "/home/sachin/Workspace/Sootballs/Translation_script/translate-po-recursive-src-dest/translate_po/main.py", line 15, in translate
    return translator.translate(source, dest=arguments.to, src=arguments.fro).text
  File "/home/sachin/.local/lib/python3.8/site-packages/googletrans/client.py", line 222, in translate
    translated_parts = list(map(lambda part: TranslatedPart(part[0], part[1] if len(part) >= 2 else []), parsed[1][0][0][5]))
TypeError: 'NoneType' object is not iterable
```

**Comment by sachin-suresh-rapyuta** [comment]
Guess you need to update the `client.py` with the `try` block as discussed [here](https://github.com/ssut/py-googletrans/issues/260#issuecomment-751521801). This seems to be working for me after this update. Checking other scenarios too.

**Comment by sachin-suresh-rapyuta** [comment]
And this leads to another error:

```
Traceback (most recent call last):
  File "translate_script.py", line 8, in <module>
    run(
  File "/home/sachin/Workspace/Sootballs/Translation_script/translate-po-recursive-src-dest/translate_po/main.py", line 61, in run
    solve(os.path.join(arguments.dest, relative_path, file), os.path.join(root, file), arguments)
  File "/home/sachin/Workspace/Sootballs/Translation_script/translate-po-recursive-src-dest/translate_po/main.py", line 27, in solve
    line.msgstr = polib.unescape(translate(polib.escape(line.msgid), arguments))
  File "/home/sachin/Workspace/Sootballs/Translation_script/translate-po-recursive-src-dest/translate_po/main.py", line 15, in translate
    return translator.translate(source, dest=arguments.to, src=arguments.fro).text
  File "/home/sachin/.local/lib/python3.8/site-packages/googletrans/client.py", line 225, in translate
    translated_parts = list(map(lambda part: TranslatedPart(part[0], part[1] if len(part) >= 2 else []), parsed[1][0][0][5]))
IndexError: list index out of range
```

**Comment by arkadianriver** [comment]
I didn’t do anything with the client.py in googletrans, I just needed to install googletrans rc1 on its own outside the other dependencies. Maybe my test content isn’t sufficient? Is your content in an open git repo that I can test?
